function FM = LAPD(Image) 
        M1 = [0,0,0;-1 2 -1;0,0,0];
        M2 = [0 0 -1;0 2 0;-1 0 0]/sqrt(2);
        M3 = [-1 0 0;0 2 0;0 0 -1]/sqrt(2);
%         F1 = fftconv(Image, M1);
%         F2 = fftconv(Image, M2);
%         F3 = fftconv(Image, M3);
%         F4 = fftconv(Image, M1');
        F1 = imfilter(Image, M1, 'replicate', 'conv');
        F2 = imfilter(Image, M2, 'replicate', 'conv');
        F3 = imfilter(Image, M3, 'replicate', 'conv');
        F4 = imfilter(Image, M1', 'replicate', 'conv');
        FM = abs(F1) + abs(F2) + abs(F3) + abs(F4);
%         IM = mean2(FM);
       weight = 1e5 * fspecial('gaussian',[size(FM,1),size(FM,2)],100);
       FM = FM.*weight;
